from __future__ import annotations

from typing import Any

from plasma_reactgen.domain.identifiers import to_file_key
from plasma_reactgen.domain.models import ReactionChannel, Species, SpeciesAmount
from plasma_reactgen.inference.scoring import confidence


def electron_parent_ionization_channel(
    target: Species,
    product_ion_id: str,
) -> ReactionChannel:
    """Build a conservative inferred parent-ionization channel."""

    return ReactionChannel(
        id=f"inferred_e_{to_file_key(target.id)}_ionization_parent",
        type="ionization",
        products=[
            SpeciesAmount(species="e", n=2.0),
            SpeciesAmount(species=product_ion_id, n=1.0),
        ],
        threshold_eV=None,
        data=_inference_data(
            rule="electron_parent_ionization",
            score=0.55,
            basis=[
                "charge_and_element_balanced",
                "generated_by_template",
                "threshold_unknown",
                "cross_section_missing",
            ],
        ),
        status="inferred",
    )


def ion_neutral_parent_charge_transfer_channel(
    projectile: Species,
    target: Species,
    neutral_projectile_id: str,
    target_cation_id: str,
) -> ReactionChannel:
    """Build a conservative inferred parent charge-transfer channel."""

    return ReactionChannel(
        id=(
            f"inferred_{to_file_key(projectile.id)}_"
            f"{to_file_key(target.id)}_charge_transfer_parent"
        ),
        type="charge_transfer",
        products=[
            SpeciesAmount(species=neutral_projectile_id, n=1.0),
            SpeciesAmount(species=target_cation_id, n=1.0),
        ],
        deltaE_products_minus_reactants_eV=None,
        dnt_class="long_range_charge_exchange",
        data=_inference_data(
            rule="ion_neutral_parent_charge_transfer",
            score=0.55,
            basis=[
                "charge_and_element_balanced",
                "generated_by_template",
                "energy_unknown",
            ],
            dnt_missing=["deltaE_products_minus_reactants_eV"],
        ),
        status="inferred",
    )


def _inference_data(
    *,
    rule: str,
    score: float,
    basis: list[str],
    dnt_missing: list[str] | None = None,
) -> dict[str, Any]:
    data: dict[str, Any] = {
        "confidence": confidence(score, basis),
        "inference": {
            "rule": rule,
            "notes": ["Candidate generated by rule, not curated data."],
        },
        "provenance": {
            "source_type": "inference",
            "source_id": None,
        },
    }
    if dnt_missing:
        data["dnt"] = {
            "status": "missing_energy",
            "missing_for_complete_dnt": list(dnt_missing),
        }
    return data
