from __future__ import annotations

from typing import Any

from plasma_reactgen.domain.formula import composition_mass_amu, parse_formula
from plasma_reactgen.domain.identifiers import to_file_key
from plasma_reactgen.domain.models import Species
from plasma_reactgen.inference.scoring import confidence


def make_parent_ion_candidates(species: Species | dict[str, Any]) -> list[dict[str, Any]]:
    """Create inferred parent cation and anion candidates for a neutral parent."""

    parent = _species_view(species)
    if parent["charge"] != 0 or not parent["id"] or not parent["composition"]:
        return []

    mass = parent["mass_amu"]
    candidates: list[dict[str, Any]] = []
    for suffix, charge, label in (("+", 1, "parent_cation"), ("-", -1, "parent_anion")):
        species_id = f"{parent['id']}{suffix}"
        candidates.append(
            {
                "kind": "species_candidate",
                "id": to_file_key(species_id),
                "display_id": species_id,
                "composition": dict(parent["composition"]),
                "charge": charge,
                "classes": ["positive_ion" if charge > 0 else "negative_ion"],
                "properties": _properties_payload(mass),
                "status": "inferred",
                "confidence": confidence(0.6, ["generated_parent_ion", "composition_copied"]),
                "inference": {
                    "rule": label,
                    "parent_species": [parent["id"]],
                    "notes": ["Candidate generated by rule, not curated data."],
                },
            }
        )
    return candidates


def make_basic_fragment_candidates(
    species: Species | dict[str, Any],
    max_fragment_depth: int = 1,
) -> list[dict[str, Any]]:
    """Create conservative one-atom-loss neutral fragment candidates."""

    parent = _species_view(species)
    if max_fragment_depth < 1 or not parent["id"] or not parent["composition"]:
        return []

    candidates: list[dict[str, Any]] = []
    for element in sorted(parent["composition"]):
        count = parent["composition"][element]
        if count <= 0:
            continue

        remaining = dict(parent["composition"])
        remaining[element] -= 1
        if remaining[element] == 0:
            del remaining[element]
        if not remaining:
            continue

        lost_atom = {element: 1}
        candidates.append(
            {
                "kind": "fragment_set_candidate",
                "id": f"{to_file_key(_formula_from_composition(remaining))}__{to_file_key(element)}",
                "parent_species": parent["id"],
                "fragments": [
                    _fragment_payload(remaining),
                    _fragment_payload(lost_atom),
                ],
                "status": "inferred",
                "confidence": confidence(
                    0.5,
                    ["single_atom_loss", "composition_balanced", "template_only_support"],
                ),
                "inference": {
                    "rule": "single_atom_loss",
                    "max_fragment_depth": max_fragment_depth,
                    "notes": ["Candidate generated by rule, not curated data."],
                },
            }
        )
    return candidates


def _species_view(species: Species | dict[str, Any]) -> dict[str, Any]:
    if isinstance(species, Species):
        mass = _species_property_value(species, "mass_amu")
        if mass is None:
            mass = composition_mass_amu(species.composition)
        return {
            "id": species.id,
            "composition": dict(species.composition),
            "charge": species.charge,
            "mass_amu": mass,
        }

    composition = dict(species.get("composition", {}))
    if not composition and species.get("formula"):
        composition = parse_formula(str(species["formula"]))
    mass = species.get("mass_amu")
    if mass is None:
        mass = _dict_property_value(species, "mass_amu")
    if mass is None:
        mass = composition_mass_amu(composition)
    return {
        "id": species.get("id") or species.get("formula"),
        "composition": composition,
        "charge": species.get("charge", 0),
        "mass_amu": mass,
    }


def _species_property_value(species: Species, name: str):
    prop = species.properties.get(name)
    return None if prop is None else prop.value


def _dict_property_value(species: dict[str, Any], name: str):
    properties = species.get("properties", {})
    prop = properties.get(name)
    if isinstance(prop, dict):
        return prop.get("value")
    return prop


def _properties_payload(mass_amu) -> dict[str, dict[str, Any]]:
    return {
        "mass_amu": {
            "value": mass_amu,
            "unit": "amu",
            "source": "parent" if mass_amu is not None else "missing",
        }
    }


def _fragment_payload(composition: dict[str, int]) -> dict[str, Any]:
    formula = _formula_from_composition(composition)
    return {
        "id": to_file_key(formula),
        "formula": formula,
        "composition": composition,
        "charge": 0,
        "mass_amu": composition_mass_amu(composition),
    }


def _formula_from_composition(composition: dict[str, int]) -> str:
    parts: list[str] = []
    for element in sorted(composition):
        count = composition[element]
        parts.append(element if count == 1 else f"{element}{count}")
    return "".join(parts)
